name: Update DockerHub Readmes on PR Merge

on:
  pull_request:
    types:
      - closed
    paths:
      - "images/**/README.md"

jobs:
  detect-readmes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      readme_files: ${{ steps.detect.outputs.readme_files }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Detect changed README files
        id: detect
        run: |
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep 'images/.*/README.md' || true)

          if [ -z "$files" ]; then
            echo "No README.md changes detected."
            echo "readme_files=[]" >> $GITHUB_OUTPUT
          else
            readme_json=$(echo "$files" | jq -R -s -c 'split("\n")[:-1]')
            echo "Detected README files: $readme_json"
            echo "readme_files=$readme_json" >> $GITHUB_OUTPUT
          fi

  push-readmes:
    needs: detect-readmes
    if: needs.detect-readmes.outputs.readme_files != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        readme_file: ${{ fromJson(needs.detect-readmes.outputs.readme_files) }}
    steps:
      - uses: actions/checkout@v4

      - name: Extract image name
        id: extract
        run: |
          IMAGE_NAME=$(basename $(dirname "${{ matrix.readme_file }}"))
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Push README to DockerHub
        uses: ./.github/workflows/_update_docker_hub_read_me.yaml
        with:
          repository: dmascot/${{ steps.extract.outputs.image_name }}
          readme_path: ${{ matrix.readme_file }}
          secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}